#!/bin/bash
if [ $# -eq 0 ]
	then
		echo "Please enter the name of the file as a command line argument."
		printf "   ex. run <program_name>\n"
		echo "Choices for this homework are:"
		printf "   1. ex01\n"
		printf "   2. ex02\n"
		exit 1
fi

CURRENT_DIRECTORY=$PWD
CURRENT_FILE="${CURRENT_DIRECTORY}/source/$1.c"
MY_LIBRARY="${CURRENT_DIRECTORY}/lib/my-lib.c"
BINARY_DIRECTORY="${CURRENT_DIRECTORY}/bin"
BINARY_FILE="${BINARY_DIRECTORY}/$1"

clear
gcc -o $BINARY_FILE $CURRENT_FILE $MY_LIBRARY
$BINARY_FILE
